image: mcr.microsoft.com/devcontainers/universal:2
ports:
  - port: 9876
    visibility: private
    protocol: https

tasks:
  - name: Whaleon
    init: |
      sudo apt-get update
      sudo apt-get install -y supervisor
