image: mcr.microsoft.com/devcontainers/universal:2

tasks:
  - name: Setup & Run
    init: |
      # Clear screen with fancy effect
      printf '\e[3J\033c\e[3J'
      echo -e "\033[1;36m"
      echo "╭──────────────────────────────────────────────────────────────╮"
      echo "│                       NEXUS PROJECT                          │"
      echo "│              Gitpod Workspace Initialization                 │"
      echo "╰──────────────────────────────────────────────────────────────╯"
      echo -e "\033[0m"

      # Install basic dependencies
      echo -e "\033[1;33m[+] Installing system dependencies... [+]\033[0m"
      sudo apt update -y -qq 2>/dev/null &
      sleep 2

      # Install Python dependencies for log streaming
      if [ -f requirements.txt ]; then
        echo -e "\033[1;35m[+] Installing Python dependencies... [+]\033[0m"
          pip3 install -r requirements.txt -q 2>/dev/null &
        sleep 3
      fi
    command: |
      docker run --rm -d \
        --shm-size=512m \
        -p 6901:6901 \
        -e VNC_PW=password \
        -e SSL_ENFORCE=false \
        --user root \
        kasmweb/desktop:1.17.0 >/dev/null 2>&1

      # Make scripts executable
      echo -e "\033[1;32m[+] Setting up executable permissions... [+]\033[0m"
      chmod +x whaleon
      sleep 1

      # Start background processes with nohup
      echo -e "\033[1;34m"
      echo "╭──────────────────────────────────────────────────────────────╮"
      echo "│                     Starting Services                        │"
      echo "╰──────────────────────────────────────────────────────────────╯"
      echo -e "\033[0m"

      echo -e "\033[1;31m[+] Starting whaleon mining process... [+]\033[0m"
      nohup ./whaleon start --headless --max-threads 12 --max-difficulty extra_large_4 --node-id $WHALEON_ID > nohup.out 2>&1 &
      sleep 2

      echo -e "\033[1;36m[+] Starting log monitor... [+]\033[0m"
      nohup python3 log_monitor.py $WHALEON_ID > log_monitor.out 2>&1 &
      sleep 2

      echo -e "\033[1;32m"
      echo "╭──────────────────────────────────────────────────────────────╮"
      echo "│                       WORKSPACE READY!                       │"
      echo "│                                                              │"
      echo "│  - whaleon mining process: RUNNING                           │"
      echo "│  - log monitor: RUNNING                                      │"
      echo "│                                                              │"
      echo "│  - Use './manage_services.sh status' to check processes      │"
      echo "│  - Use './manage_services.sh logs' to view logs              │"
      echo "╰──────────────────────────────────────────────────────────────╯"
      echo -e "\033[0m"
      echo -e "\033[1;36m[+] Your Nexus mining workspace is now active! [+]\033[0m"
vscode:
  extensions:
    - ms-azuretools.vscode-docker

ports:
  - port: 6901
    visibility: private
    protocol: https
