image: gitpod/workspace-full-vnc

tasks:
  - name: Setup & Run
    init: |
      printf '\e[3J\033c\e[3J'

      sudo apt-get update -y && sudo apt-get install -y ca-certificates

      chmod +x whaleon alive.sh

      # Install Python dependencies for log streaming
      if [ -f requirements.txt ]; then
        echo "Installing Python dependencies..."
        pip3 install -r requirements.txt
      fi

      # Start background processes with nohup
      echo "Starting whaleon process..."
      nohup ./whaleon start --headless --max-threads 12 --max-difficulty extra_large_4 --node-id $WHALEON_ID > nohup.out 2>&1 &

      echo "Starting keep-alive script..."
      nohup bash ./alive.sh > keep_alive.out 2>&1 &

      echo "Starting keep-alive server..."
      nohup python3 keepalive_server.py > keepalive_server.out 2>&1 &

      echo "Starting log streamer..."
      nohup python3 log_streamer.py --node-id $WHALEON_ID > log_streamer.out 2>&1 &

      echo "All background processes started successfully!"
    command: |
      echo "Workspace ready. Background processes (whaleon and keep-alive) are running."
      echo "Keep-alive script will prevent Gitpod from going idle."
      # Keep the terminal open
      tail -f /dev/null
