image: gitpod/workspace-full-vnc

tasks:
  - name: Setup & Run
    init: |
      sudo apt-get update -y && sudo apt-get install -y xdotool xvfb ca-certificates
      
      export DISPLAY=:99
      echo "export DISPLAY=:99" >> ~/.bashrc
      chmod +x whaleon alive.sh
      
      nohup ./whaleon start --headless --max-threads 2 --max-difficulty extra_large_2 --node-id 2>&1 &
      bash ./alive.sh 2>&1 &
    command: |
      echo "Workspace ready. Background processes whaleon are running."
ports:
    - name: ws
      port: 6969
      onOpen: ignore
      visibility: public
