image: gitpod/workspace-full-vnc
ports:
  - port: 9876
    visibility: public
    protocol: http

tasks:
  - name: Whaleon
    init: |
      sudo apt-get update && sudo apt-get install -y supervisor
      sudo export ID=$ID
