image: gitpod/workspace-full-vnc

tasks:
  - name: Setup & Run
    init: |
      sudo apt-get update -y && sudo apt-get install -y xdotool xvfb ca-certificates
      
      Xvfb :99 -screen 0 1024x768x16 &
      export DISPLAY=:99
      echo "export DISPLAY=:99" >> ~/.bashrc
      
      sudo chmod +x whaleon
      sudo chmod +x alive.sh
      
      nohup ./whaleon 2>&1 &
      nohup bash ./alive.sh 2>&1 &
    command: |
      echo "Workspace ready. Background processes whaleon are running."
