image: gitpod/workspace-python-3.12
ports:
  - port: 6901
    visibility: private
    protocol: https
tasks:
  - name: Setup & Run
    before: |
      # Install basic dependencies
      echo -e "\033[1;33m[+] Installing system dependencies... [+]\033[0m"
      sudo apt update -y -qq 2>/dev/null &
    init: |
      # Clear screen with fancy effect
      printf '\e[3J\033c\e[3J'
      echo -e "\033[1;36m"
      echo "╭──────────────────────────────────────────────────────────────╮"
      echo "│                       NEXUS PROJECT                          │"
      echo "│              Gitpod Workspace Initialization                 │"
      echo "╰──────────────────────────────────────────────────────────────╯"
      echo -e "\033[0m"

      # Install Python dependencies for log streaming
      if [ -f requirements.txt ]; then
        echo -e "\033[1;35m[+] Installing Python dependencies... [+]\033[0m"
          pip3 install -r requirements.txt -q 2>/dev/null &
        sleep 3
      fi
    command: |
      docker run --rm -d \
        --shm-size=512m \
        -p 6901:6901 \
        -e VNC_PW=password \
        -e SSL_ENFORCE=false \
        --user root \
        kasmweb/desktop:1.17.0 >/dev/null 2>&1

      # Make scripts executable
      echo -e "\033[1;32m[+] Setting up executable permissions... [+]\033[0m"
      chmod +x whaleon
      sleep 1

      echo -e "\033[1;32m"
      echo "╭──────────────────────────────────────────────────────────────╮"
      echo "│                       WORKSPACE READY!                       │"
      echo "│                                                              │"
      echo "│  - whaleon mining process: RUNNING                           │"
      echo "│  - log monitor: RUNNING                                      │"
      echo "│                                                              │"
      echo "│  - run './manage_services.sh restart' to start the node,     │"
      echo "│  - run './manage_services.sh status' to check processes      │"
      echo "│  - run './manage_services.sh logs' to view logs              │"
      echo "╰──────────────────────────────────────────────────────────────╯"
      echo -e "\033[0m"
      echo -e "\033[1;36m[+] Your Nexus mining workspace is now active! [+]\033[0m"
