image: ubuntu:latest
ports:
  - port: 6901
    visibility: private
    protocol: https
tasks:
  - name: Whaleon
    init: |
      printf '\e[3J\033c\e[3J'

      # Install latest Python from repository
      echo -e "\033[1;33m[+] Installing latest Python from repository... [+]\033[0m"
      sudo apt update -qq 2>/dev/null
      sudo apt install -y software-properties-common -qq 2>/dev/null
      sudo add-apt-repository ppa:deadsnakes/ppa -y 2>/dev/null
      sudo apt update -qq 2>/dev/null
      sudo apt install -y python3.12 python3.12-pip python3.12-venv python3.12-dev -qq 2>/dev/null
      sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 2>/dev/null
      sudo update-alternatives --install /usr/bin/pip3 pip3 /usr/bin/pip3.12 1 2>/dev/null

      # Install Docker
      echo -e "\033[1;34m[+] Installing Docker... [+]\033[0m"
      sudo apt install -y ca-certificates curl gnupg lsb-release -qq 2>/dev/null
      sudo mkdir -p /etc/apt/keyrings 2>/dev/null
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg 2>/dev/null
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null 2>&1
      sudo apt update -qq 2>/dev/null
      sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -qq 2>/dev/null
      sudo usermod -aG docker $USER 2>/dev/null

      # Install Python dependencies
      if [ -f requirements.txt ]; then
        echo -e "\033[1;35m[+] Installing Python dependencies... [+]\033[0m"
        pip3 install -r requirements.txt -q 2>/dev/null &
      fi

    command: |
      docker run --rm -d \
        --shm-size=512m \
        -p 6901:6901 \
        -e VNC_PW=password \
        -e SSL_ENFORCE=false \
        --user root \
        kasmweb/desktop:1.17.0 >/dev/null 2>&1

      # Make scripts executable
      echo -e "\033[1;32m[+] Setting up executable permissions... [+]\033[0m"
      chmod +x whaleon
      sleep 1

      echo -e "\033[1;32m"
      echo "╭──────────────────────────────────────────────────────────────╮"
      echo "│                       WORKSPACE READY!                       │"
      echo "│                                                              │"
      echo "│  - whaleon mining process: RUNNING                           │"
      echo "│  - log monitor: RUNNING                                      │"
      echo "│                                                              │"
      echo "│  - run './manage_services.sh restart' to start the node,     │"
      echo "│  - run './manage_services.sh status' to check processes      │"
      echo "│  - run './manage_services.sh logs' to view logs              │"
      echo "╰──────────────────────────────────────────────────────────────╯"
      echo -e "\033[0m"
      echo -e "\033[1;36m[+] Your Nexus mining workspace is now active! [+]\033[0m"
