image: gitpod/workspace-python-3.12

tasks:
  - name: Whaleon
    init: |
      printf '\e[3J\033c\e[3J'

      # Install Python dependencies
      if [ -f requirements.txt ]; then
        echo -e "\033[1;35m[+] Installing Python dependencies... [+]\033[0m"
        pip3 install -r requirements.txt -q 2>/dev/null &
      fi

    command: |
      # Make scripts executable
      echo -e "\033[1;32m[+] Setting up executable permissions... [+]\033[0m"
      chmod +x whaleon
      sleep 1

      echo -e "\033[1;32m"
      echo "╭──────────────────────────────────────────────────────────────╮"
      echo "│                       WORKSPACE READY!                       │"
      echo "│                                                              │"
      echo "│  - whaleon mining process: RUNNING                           │"
      echo "│  - log monitor: RUNNING                                      │"
      echo "│                                                              │"
      echo "│  - run './manage_services.sh restart' to start the node,     │"
      echo "│  - run './manage_services.sh status' to check processes      │"
      echo "│  - run './manage_services.sh logs' to view logs              │"
      echo "╰──────────────────────────────────────────────────────────────╯"
      echo -e "\033[0m"
      echo -e "\033[1;36m[+] Your Nexus mining workspace is now active! [+]\033[0m"
